export enum MeterReadingActionTypes {
  GET_METER_READING = "GET_METER_READING",
  GET_METER_READING_SUCCEEDED="GET_METER_READING_SUCCEEDED",
  GET_METER_READING_FAILED="GET_METER_READING_FAILED",
}

