export const categoryModules: { [key: string]: string[] } = {
  settings: [
    "MOD-29",
    "MOD-30",
    "MOD-31",
    "MOD-32",
    "MOD-33",
    "MOD-34",
    "MOD-35",
    "MOD-36",
    "MOD-37",
    "MOD-38",
    "MOD-39",
    "MOD-40",
    "MOD-41",
    "MOD-42",
    "MOD-43",
    "MOD-44",
    "MOD-45",
    "MOD-47",
    "MOD-48",
  ],
  transactions: ["MOD-21", "MOD-22", "MOD-23", "MOD-24"],
  payments: [
    "MOD-1",
    "MOD-2",
    "MOD-3",
    "MOD-4",
    "MOD-5",
    "MOD-6",
    "MOD-7",
    "MOD-8",
    "MOD-9",
    "MOD-10",
    "MOD-11",
  ],
  audit: ["MOD-25", "MOD-26"],
  trends: ["MOD-27", "MOD-28"],
  overview: ["MOD-46"],
  bills: ["MOD-12", "MOD-13", "MOD-14", "MOD-15", "MOD-16", "MOD-17"],
  beneficiaries: ["MOD-18", "MOD-19", "MOD-20"],
  reconciliation: ["MOD-53", "MOD-54", "MOD-55"],
};

export const superAdminRoutes: string[] = [
  "overview",
  "masterdata",
  "userprofile",
  "reports",
];
